name: 'Release Creator'
description: 'Creates a GitHub release'
branding:
  icon: package
  color: gray-dark
inputs:
  type:
    description:
      'The release type to create (Major|Minor|Patch)'
    required: true
  token:
    description:
      'The access token for authenticating against GitHub'
    required: true
  pre-release:
    description:
      'Indicates if this release is a pre-release'
    required: true
  pre-release-identifier:
    description:
      'The pre-release identifier'
    required: false
  log-level:
    description:
      'Configures the log level (default: information)'
    required: false
    default: 'Information'
outputs:
  next-version:
    description: 'The next semantic version created by this action'

runs:
  env:
    Logging__LogLevel__Default: "${{ inputs.log-level }}"
  using: 'docker'
  # image: 'docker://ghcr.io/jhin-mista/releasecreator:v0' # This works once the repository is public
  image: 'Dockerfile'
  args:
    - '--commit'
    - ${{ github.sha }}
    - '--type'
    - ${{ inputs.type }}
    - '--token'
    - ${{ inputs.token }}
    - ${{ inputs.pre-release == 'true' && '--pre-release' || null }}
    - ${{ inputs.pre-release == 'true' && inputs.pre-release-identifier || null }}