name: Feature Request Form (Beta)
description: Suggest an idea for this project.
title: "[Feature request]: "
labels: ["enhancement"]
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to suggest an idea for this project!
 - type: textarea
   id: description
   attributes:
     label: Description
     description: Is your feature request related to a problem? Please describe.
     placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
 - type: textarea
   id: proposed-solution
   attributes:
     label: Proposed solution
     description: "Describe the solution you'd like"
     placeholder: "A clear and concise description of what you want to happen."
 - type: textarea
   id: alternatives
   attributes:
     label: Possible alternatives
     description: "Describe alternatives you've considered"
     placeholder: "A clear and concise description of any alternative solutions or features you've considered."
 - type: textarea
   id: additional-context
   attributes:
     label: Additional context
     description: "Add any other context or screenshots about the feature request here."
     
