name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUN: "docker compose --file test/compose.yaml run --rm"
  BUILD: "docker compose --file test/compose.yaml build"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Setup git
      run: |
       git config --global core.autocrlf false
       git config --global core.eol crlf

    - name: Check out
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: $RUN restore

    - name: Format
      run: $RUN format

    - name: Build
      run: $RUN build

    - name: Test
      run: $RUN tests

    - name: Build prod image
      run: $BUILD prod-build