name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_COMPOSE: "docker compose --file test/compose.yaml"
  RUN: "$DOCKER_COMPOSE run --rm"
  BUILD: "$DOCKER_COMPOSE build"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Setup git
      run: |
       git config --global core.autocrlf false
       git config --global core.eol crlf

    - name: Check out
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Restore dependencies
      run: $RUN restore

    - name: Format
      run: $RUN format

    - name: Build
      run: $RUN build

    - name: Test
      run: $RUN tests

    - name: Build prod image
      run: $BUILD prod-build