name: Create release

on:
    workflow_dispatch: 
        inputs:
            release-type:
                description: The type of release
                type: choice
                required: true
                options:
                    - Major
                    - Minor
                    - Patch
            is-pre-release:
                description: Indicates if this is a pre-release
                type: boolean
                required: true
                default: false
            pre-release-identifier:
                description: An optional pre-release identifier
                type: string
                required: false
                default: ""

jobs:
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Call release creator action
              id: release-creator
              if: ${{ github.ref_type == 'branch' }}
              uses: ./
              with:
                branch: ${{ github.ref_name }}
                type: ${{ inputs.release-type }}
                token: ${{ secrets.GITHUB_TOKEN }}
                pre-release: ${{ github.event.inputs.is-pre-release }}
                pre-release-identifier: ${{ inputs.pre-release-identifier }}
                log-level: Debug

            - name: Build container image
              run: "docker build -t ghcr.io/jhin-mista/releasecreator:latest -t ghcr.io/jhin-mista/releasecreator:${{ steps.release-creator.outputs.next-version }} ."

            - name: Push container image
              run: "docker push --all-tags ghcr.io/jhin-mista/releasecreator"