name: Create release

on:
    workflow_dispatch: 
        inputs:
            release-type:
                description: The type of release
                type: choice
                required: true
                options:
                    - Major
                    - Minor
                    - Patch
            is-pre-release:
                description: Indicates if this is a pre-release
                type: boolean
                required: true
                default: false
            pre-release-identifier:
                description: An optional pre-release identifier
                type: string
                required: false
                default: ""

jobs:
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: jhin-mista/releasecreator
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Container registry login
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Call release creator action
              id: release-creator
              uses: ./
              with:
                commit: ${{ github.sha }}
                type: ${{ inputs.release-type }}
                token: ${{ secrets.GITHUB_TOKEN }}
                pre-release: ${{ github.event.inputs.is-pre-release }}
                pre-release-identifier: ${{ inputs.pre-release-identifier }}
                log-level: Debug

            - name: Get major version tag
              id: get-major-version-tag
              run: |
                major_version_tag=$(echo ${{ steps.release-creator.outputs.next-version }} | cut -d. -f1)
                echo "MAJOR_VERSION_TAG=$major_version_tag" >> $GITHUB_OUTPUT

            - name: Setup docker builder
              uses: docker/setup-buildx-action@v3

            - name: Build and push container image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.release-creator.outputs.next-version }}
                  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-major-version-tag.outputs.MAJOR_VERSION_TAG }}
                provenance: false
                sbom: false